-- Expense workflow: draft -> submitted -> approved|rejected (or returned to
-- draft for correction) -> paid. The financial engine is only ever touched
-- at the 'paid' transition (expenses.service.js#payExpense) — draft,
-- submitted, approved, and rejected expenses have zero ledger effect.
CREATE TABLE expenses (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  tenant_id BIGINT UNSIGNED NOT NULL,
  expense_number VARCHAR(50) NOT NULL,
  category_id BIGINT UNSIGNED NOT NULL,
  fund_id BIGINT UNSIGNED NOT NULL,
  account_id BIGINT UNSIGNED NOT NULL,
  amount DECIMAL(14, 2) NOT NULL,
  payee VARCHAR(255) NOT NULL,
  description VARCHAR(500) NULL,
  payment_method VARCHAR(50) NOT NULL,
  reference VARCHAR(100) NULL,
  attachment_url VARCHAR(500) NULL,
  attachment_mime VARCHAR(100) NULL,
  attachment_size_bytes INT UNSIGNED NULL,
  status ENUM('draft', 'submitted', 'approved', 'rejected', 'paid') NOT NULL DEFAULT 'draft',
  requested_by_user_id BIGINT UNSIGNED NOT NULL,
  approved_by_user_id BIGINT UNSIGNED NULL,
  approval_date DATETIME NULL,
  rejected_by_user_id BIGINT UNSIGNED NULL,
  rejection_reason VARCHAR(500) NULL,
  paid_by_user_id BIGINT UNSIGNED NULL,
  payment_date DATETIME NULL,
  transaction_id BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  UNIQUE KEY uq_expenses_tenant_number (tenant_id, expense_number),
  UNIQUE KEY uq_expenses_transaction (transaction_id),
  KEY idx_expenses_tenant_status (tenant_id, status),
  KEY idx_expenses_tenant_requested_by (tenant_id, requested_by_user_id),
  CONSTRAINT fk_expenses_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE RESTRICT,
  CONSTRAINT fk_expenses_category FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE RESTRICT,
  CONSTRAINT fk_expenses_fund FOREIGN KEY (fund_id) REFERENCES funds (id) ON DELETE RESTRICT,
  CONSTRAINT fk_expenses_account FOREIGN KEY (account_id) REFERENCES accounts (id) ON DELETE RESTRICT,
  CONSTRAINT fk_expenses_requested_by FOREIGN KEY (requested_by_user_id) REFERENCES users (id) ON DELETE RESTRICT,
  CONSTRAINT fk_expenses_approved_by FOREIGN KEY (approved_by_user_id) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT fk_expenses_rejected_by FOREIGN KEY (rejected_by_user_id) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT fk_expenses_paid_by FOREIGN KEY (paid_by_user_id) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT fk_expenses_transaction FOREIGN KEY (transaction_id) REFERENCES transactions (id) ON DELETE RESTRICT,
  CONSTRAINT chk_expenses_amount_positive CHECK (amount > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
