// The full permission catalog. Inert data until Phase 2 wires RBAC
// enforcement — seeded now so the schema is complete and stable from Phase 1.
// Source: Phase 2 brief's permission list, plus a few structurally implied
// additions noted inline.
export const PERMISSIONS = [
  ['dashboard.view', 'View the dashboard'],
  ['income.view', 'View income/contribution records'],
  ['income.create', 'Record income/contributions'],
  ['income.update', 'Edit a posted contribution\'s non-financial detail (notes, reference, contributor link) — never its amount/account/fund/category, which are immutable once posted; use income.reverse for financial corrections'],
  ['income.reverse', 'Reverse a posted income transaction'],
  ['contributors.view', 'View the contributor/donor directory (name, phone, email) — separate from income.view so financial amounts can be visible without exposing donor identity'],
  ['contributors.manage', 'Create/edit contributor records'],
  ['expense.view', 'View expense records'],
  ['expense.create', 'Create expense requests'],
  ['expense.update', 'Edit a draft expense before submission'],
  ['expense.submit', 'Submit an expense into the approval chain'],
  ['expense.approve', 'Approve a pending expense'],
  ['expense.reject', 'Reject a pending expense'],
  ['expense.pay', 'Mark an approved expense as paid (posts the ledger entry)'],
  ['accounts.view', 'View accounts (bank/cash/mobile money)'],
  ['accounts.manage', 'Create/edit accounts'],
  ['funds.view', 'View funds'],
  ['funds.manage', 'Create/edit funds'],
  ['categories.manage', 'Create/edit income and expense categories'],
  ['transfers.create', 'Create transfers between accounts/funds'],
  ['pledges.view', 'View pledges'],
  ['pledges.create', 'Create pledges'],
  ['receipts.view', 'View/download receipts'],
  ['reports.view', 'View reports'],
  ['reports.export', 'Export reports (PDF/Excel/CSV)'],
  ['budget.view', 'View budgets'],
  ['budget.manage', 'Create/edit budgets'],
  ['financial_period.close', 'Close a financial period'],
  ['financial_period.reopen', 'Reopen a closed financial period (elevated, distinct from close)'],
  ['users.view', 'View tenant users'],
  ['users.manage', 'Invite/disable users, assign roles'],
  ['roles.manage', 'Manage custom roles and their permissions'],
  ['settings.manage', 'Manage church settings'],
  ['audit.view', 'View the audit log'],
];

// System-default roles. tenant_id NULL — shared across every tenant.
// "ALL" grants every permission in the catalog above.
export const SYSTEM_ROLES = {
  'Super Administrator': 'ALL',
  'Treasurer': [
    'dashboard.view',
    'income.view', 'income.create', 'income.update', 'income.reverse',
    'contributors.view', 'contributors.manage',
    'expense.view', 'expense.create', 'expense.update', 'expense.submit', 'expense.pay',
    'accounts.view', 'accounts.manage',
    'funds.view', 'funds.manage',
    'categories.manage',
    'transfers.create',
    'pledges.view', 'pledges.create',
    'receipts.view',
    'reports.view', 'reports.export',
    'budget.view', 'budget.manage',
    'financial_period.close',
  ],
  'Assistant Treasurer': [
    'dashboard.view',
    'income.view', 'income.create',
    'contributors.view',
    'expense.view', 'expense.create', 'expense.submit',
    'accounts.view',
    'funds.view',
    'pledges.view', 'pledges.create',
    'receipts.view',
    'reports.view',
    'budget.view',
  ],
  'Approver': [
    'dashboard.view',
    'expense.view', 'expense.approve', 'expense.reject',
    'reports.view',
  ],
  'Auditor': [
    'dashboard.view',
    'income.view', 'expense.view',
    'accounts.view', 'funds.view',
    'pledges.view', 'receipts.view',
    'reports.view', 'reports.export',
    'budget.view',
    'audit.view',
  ],
  'Viewer': [
    'dashboard.view',
    'income.view', 'expense.view',
    'accounts.view', 'funds.view',
    'pledges.view', 'receipts.view',
    'reports.view', 'budget.view',
  ],
};
