-- Clix Church Treasury Management System — PRODUCTION database setup.
--
-- This deployment's actual requirement: the application connects as
-- MySQL `root` against a database named `treasurer`. This script does
-- exactly one thing — create that database — and deliberately does NOT
-- create a user or touch root's password: root already exists, and the
-- password is entered manually into server/.env by whoever runs this
-- deployment (never asked for, never guessed, never written here).
--
-- Run once, manually, as MySQL root, directly on the production host:
--   mysql -u root -p < server/scripts/setup-db.production.sql
-- (copy this file to setup-db.production.sql first — that copy is
-- gitignored; this committed template never contains a real password
-- because it never contains a password at all.)

CREATE DATABASE IF NOT EXISTS treasurer
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- That's it. No CREATE USER, no GRANT — root already has full access to
-- every database on this instance, including this new one.
--
-- ------------------------------------------------------------------
-- Security note (documented per docs/MASTER_TODO.md Phase 12 §18, not a
-- blocker — this deployment intentionally uses root):
--
-- A dedicated, least-privilege application user is the more defensible
-- long-term setup — it can't touch any database but this one, can't
-- GRANT, can't manage other MySQL users, and limits blast radius if the
-- application's DB credentials ever leaked. If that's ever wanted later,
-- the pattern is a two-line addition and needs no code change (the app
-- already reads DB_USER from the environment with no special-casing):
--
--   CREATE USER 'clix_app'@'localhost' IDENTIFIED BY 'CHANGE_ME';
--   GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX,
--     REFERENCES, DROP ON treasurer.* TO 'clix_app'@'localhost';
--
-- then set DB_USER=clix_app / DB_PASSWORD=<that password> in server/.env
-- instead of the root credentials. Entirely optional — the application
-- works correctly with DB_USER=root today.
-- ------------------------------------------------------------------

-- Next steps (see docs/DEPLOYMENT.md for the full walkthrough):
--   1. Put DB_NAME=treasurer, DB_USER=root, DB_PASSWORD=<your root
--      password> into server/.env (never into this file or git).
--   2. cd server && npm run migrate    (applies every migration in
--      src/db/migrations/, in order, idempotent — safe to re-run)
--   3. npm run seed                     (seeds the permission catalog +
--      system roles — required before any tenant can register; skips
--      the dev demo tenant automatically when NODE_ENV=production)
--   4. npm run db:check                 (verifies connection, database
--      name, migration state, and that core tables exist)
--   5. The first real tenant is created by an admin visiting the app and
--      using the church registration screen — there is no separate
--      "create the first church" CLI step.
